# Generated by Django 3.1.5 on 2021-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('image_url', models.URLField()),
                ('language', models.CharField(choices=[('tamil', 'Tamil, the ancient language'), ('english', 'English, the language of the world')], max_length=10)),
                ('wroteAt', models.DateTimeField()),
            ],
        ),
    ]
