# Generated by Django 3.1.5 on 2021-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems',
            name='image_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='poems',
            name='wroteAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
