# Generated by Django 3.1.5 on 2021-01-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20210117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems',
            name='content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='poems',
            name='language',
            field=models.CharField(blank=True, choices=[('tamil', 'Tamil, the ancient language'), ('english', 'English, the language of the world')], max_length=10, null=True),
        ),
    ]
