# Generated by Django 3.1.5 on 2021-01-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_auto_20210117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='poems',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
