# Generated by Django 3.1.5 on 2021-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poems_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
